module: Checksum
author: 9Labs
github_url: https://github.com/rnine/Checksum

theme: fullwidth
clean: true

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Checksum.xcodeproj, -target, Checksum]
